### ISSUE TITLE
Question about Hourly CIMIS "Hour" column

### ISSUE THREAD

**Issue by ikendoit** [mkoohafkan/cimir#5]
Hello everyone, 

Thank you for making this package, it is a great reference code base for what I am building at the moment, lots of neat ideas!

I have a question about the "Hour" column of the hourly data from CIMIS:

- The "Hour" column has values within (0100, 0200, ... 2400)
- Does 0100 mean 1 A.M?
- And does 2400 equate to "midnight" of that day, or 0 A.M of the next day? 

From this code, as well as looking at the usage of `cimis_to_datetime()`, it seems like that is the case, but wanted to confirm.
https://github.com/mkoohafkan/cimir/blob/d75c7a52ef049cad7896f9040ae69e6b7c553e97/R/util.r#LC24:~:text=cimis_to_datetime%20%3D%20function(d)%20%7B 

I tried to look for documentations about this column, but couldn't see any.

**Comment by mkoohafkan** [comment]
R (usually) uses the POSIX format to handle timestamps. In the POSIX format, the timestamps for a single day range from 00:00:00 to 23:59:59 (let's ignore milliseconds here). So the last minute of January 1st, 2021 would be `2021-01-01 23:59:59` and the first minute of January 2nd, 2021 would be `2021-01-02 00:00:00`. The term "midnight" corresponds to the POSIX time `00:00:00`.

CIMIS does not use the POSIX format, they use the 24-hour clock or "military time" which can use either hour 0000 or hour 2400 to specify "midnight". R's built-in conversion function `as.POSIXct()` is already designed to handle this:
```r
as.POSIXct("2021-01-01 24:00:00", tz = "UTC")
## [1] "2021-01-02 UTC"
```
i.e., `2021-01-01 24:00:00` gets converted to `2021-01-02 00:00:00`.

**Comment by ikendoit** [comment]
I see, thank you so much @mkoohafkan ! 

So the assumption I listed are correct. Your detailed answer will definitely improve the accuracy of the program I am writing.
